/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tof_example_LibDivsufsortNative */

#ifndef _Included_org_tof_example_LibDivsufsortNative
#define _Included_org_tof_example_LibDivsufsortNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tof_example_LibDivsufsortNative
 * Method:    divsufsort
 * Signature: ([B[II)I
 */
JNIEXPORT jint JNICALL Java_org_tof_example_LibDivsufsortNative_divsufsort
  (JNIEnv *, jobject, jbyteArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
